export const GET_CARD_REQUEST = 'GET_CARD_REQUEST';
export const GET_CARD_SUCCESS = 'GET_CARD_SUCCESS';
export const GET_CARD_FAILED = 'GET_CARD_FAILED';

export const CARD_ITEM_ADD = 'CARD_ITEM_ADD';
